In [1]:

def extract_filename(path):
    """
    Extracts the filename without extension from a given file path.

    Parameters:
    path (str): The file path from which to extract the filename.

    Returns:
    str: The filename without its extension.
    """
    import os
    # Extract the base name of the file (e.g., 'AZ_Glendale.txt')
    base_name = os.path.basename(path)
    # Split the base name by '.' and return the first part (e.g., 'AZ_Glendale')
    return os.path.splitext(base_name)[0]


import re

def insert_spaces(text):
    return re.sub(r'(?<!^)(?=[A-Z])', ' ', text)


import pandas as pd

# Load the Excel file
excel_path = r"C:\Users\clint\Desktop\NZLUD_Checker\august 12\combined_aug7.xlsx"
excel_df = pd.read_excel(excel_path)

# Load the CSV file
csv_path = r"C:\Users\clint\Desktop\NZLUD_Checker\old\Wills_R_nzlud\nzlud_muni.csv"
csv_df = pd.read_csv(csv_path, encoding='latin1')



# Assuming df is your DataFrame and extract_filename is already defined
# Apply the extract_filename function to the 'muni' column
excel_df['muni'] = excel_df['muni'].apply(extract_filename)

# If you want to store the result in a new column, you can do:
# df['muni_extracted'] = df['muni'].apply(extract_filename)
excel_df
excel_df_sorted = excel_df.sort_values('muni')
excel_df_sorted
csv_df = csv_df.iloc[:, :3]

csv_df = csv_df.sort_values(by=['statename', 'place'])
csv_df
csv_df = csv_df.reset_index(drop=True)
excel_df_sorted = excel_df_sorted.reset_index(drop=True)
csv_df
excel_df_sorted
combined_df = pd.concat([csv_df, excel_df_sorted], axis=1)
combined_df['place'] = combined_df['place'].apply(insert_spaces)

combined_df

,GEOID,statename,place,muni,restrict_NA_permit,restrict_NA_units,limit_NA_dwellings,limit_NA_dwelling_units
0,203000,AK,Anchorage,AK_Anchorage,0,0,0,0
1,233140,AK,Homer,AK_Homer,0,0,0,0
2,238420,AK,Kenai,AK_Kenai,0,0,0,0
3,258660,AK,Palmer,AK_Palmer,0,0,0,0
4,260310,AK,Petersburg,AK_Petersburg,0,0,0,0
...,...,...,...,...,...,...,...,...
2634,5621125,WY,Douglas,WY_Douglas,0,0,0,0
2635,5640120,WY,Jackson,WY_Jackson,0,0,0,0
2636,5644760,WY,Lander,WY_Lander,0,0,0,0
2637,5645050,WY,Laramie,WY_Laramie,0,0,0,0
2638,5663900,WY,Rawlins,WY_Rawlins,0,0,0,0

In [2]:
combined_df['GEOID'] = combined_df['GEOID'].astype(str).str.zfill(7)
combined_df

,GEOID,statename,place,muni,restrict_NA_permit,restrict_NA_units,limit_NA_dwellings,limit_NA_dwelling_units
0,0203000,AK,Anchorage,AK_Anchorage,0,0,0,0
1,0233140,AK,Homer,AK_Homer,0,0,0,0
2,0238420,AK,Kenai,AK_Kenai,0,0,0,0
3,0258660,AK,Palmer,AK_Palmer,0,0,0,0
4,0260310,AK,Petersburg,AK_Petersburg,0,0,0,0
...,...,...,...,...,...,...,...,...
2634,5621125,WY,Douglas,WY_Douglas,0,0,0,0
2635,5640120,WY,Jackson,WY_Jackson,0,0,0,0
2636,5644760,WY,Lander,WY_Lander,0,0,0,0
2637,5645050,WY,Laramie,WY_Laramie,0,0,0,0
2638,5663900,WY,Rawlins,WY_Rawlins,0,0,0,0

In [3]:
import geopandas as gpd
import matplotlib.pyplot as plt
import os
import pandas as pd

# List of paths to compressed shapefiles
compressed_shapefile_paths = [
    f'C:\\Users\\clint\\Desktop\\NZLUD_Checker\\FIPS\\tl_2010_{str(i).zfill(2)}_place10.zip'
    for i in range(1, 79)
]

# Initialize an empty list to store GeoDataFrames
gdfs = []

# Loop through each compressed file path, try to read the shapefile, and append the GeoDataFrame to the list if successful
for path in compressed_shapefile_paths:
    try:
        if os.path.exists(path):
            gdf = gpd.read_file(f"zip://{path}")
            gdfs.append(gdf)
        else:
            print(f"File not found: {path}")
    except Exception as e:
        print(f"Error reading {path}: {e}")

# Concatenate all GeoDataFrames into a single GeoDataFrame
combined_gdf = gpd.GeoDataFrame(pd.concat(gdfs, ignore_index=True))
combined_gdf

File not found: C:\Users\clint\Desktop\NZLUD_Checker\FIPS\tl_2010_03_place10.zip
File not found: C:\Users\clint\Desktop\NZLUD_Checker\FIPS\tl_2010_07_place10.zip
File not found: C:\Users\clint\Desktop\NZLUD_Checker\FIPS\tl_2010_14_place10.zip
File not found: C:\Users\clint\Desktop\NZLUD_Checker\FIPS\tl_2010_43_place10.zip
File not found: C:\Users\clint\Desktop\NZLUD_Checker\FIPS\tl_2010_52_place10.zip
File not found: C:\Users\clint\Desktop\NZLUD_Checker\FIPS\tl_2010_57_place10.zip
File not found: C:\Users\clint\Desktop\NZLUD_Checker\FIPS\tl_2010_58_place10.zip
File not found: C:\Users\clint\Desktop\NZLUD_Checker\FIPS\tl_2010_59_place10.zip
File not found: C:\Users\clint\Desktop\NZLUD_Checker\FIPS\tl_2010_61_place10.zip
File not found: C:\Users\clint\Desktop\NZLUD_Checker\FIPS\tl_2010_62_place10.zip
File not found: C:\Users\clint\Desktop\NZLUD_Checker\FIPS\tl_2010_63_place10.zip
File not found: C:\Users\clint\Desktop\NZLUD_Checker\FIPS\tl_2010_64_place10.zip
File not found: C:\Users\clint\Desktop\NZLUD_Checker\FIPS\tl_2010_65_place10.zip
File not found: C:\Users\clint\Desktop\NZLUD_Checker\FIPS\tl_2010_67_place10.zip
File not found: C:\Users\clint\Desktop\NZLUD_Checker\FIPS\tl_2010_68_place10.zip
File not found: C:\Users\clint\Desktop\NZLUD_Checker\FIPS\tl_2010_70_place10.zip
File not found: C:\Users\clint\Desktop\NZLUD_Checker\FIPS\tl_2010_71_place10.zip
File not found: C:\Users\clint\Desktop\NZLUD_Checker\FIPS\tl_2010_73_place10.zip
File not found: C:\Users\clint\Desktop\NZLUD_Checker\FIPS\tl_2010_74_place10.zip
File not found: C:\Users\clint\Desktop\NZLUD_Checker\FIPS\tl_2010_75_place10.zip
File not found: C:\Users\clint\Desktop\NZLUD_Checker\FIPS\tl_2010_76_place10.zip
File not found: C:\Users\clint\Desktop\NZLUD_Checker\FIPS\tl_2010_77_place10.zip

,STATEFP10,PLACEFP10,PLACENS10,GEOID10,NAME10,NAMELSAD10,LSAD10,CLASSFP10,PCICBSA10,PCINECTA10,MTFCC10,FUNCSTAT10,ALAND10,AWATER10,INTPTLAT10,INTPTLON10,geometry
0,01,80376,02406847,0180376,Webb,Webb town,43,C1,N,N,G4110,A,29526113,0,+31.2576050,-085.2893794,"POLYGON ((-85.25542 31.2698, -85.25556 31.2612..."
1,01,64152,02407196,0164152,Rehobeth,Rehobeth town,43,C1,N,N,G4110,A,19635705,80600,+31.1245953,-085.4397997,"MULTIPOLYGON (((-85.41918 31.16249, -85.41884 ..."
2,01,45904,02406075,0145904,Madrid,Madrid town,43,C1,N,N,G4110,A,5025806,0,+31.0357714,-085.3978454,"POLYGON ((-85.38144 31.03881, -85.38145 31.037..."
3,01,40072,02405953,0140072,Kinsey,Kinsey town,43,C1,N,N,G4110,A,31343903,0,+31.2926618,-085.3354729,"POLYGON ((-85.31545 31.31243, -85.30191 31.311..."
4,01,44344,02406049,0144344,Louisville,Louisville town,43,C1,N,N,G4110,A,7118467,0,+31.7810467,-085.5583357,"POLYGON ((-85.55096 31.80421, -85.55074 31.804..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
29788,78,27000,02651573,7827000,Coral Bay,Coral Bay CDP,57,U1,N,N,G4210,S,4756991,975009,+18.3451921,-064.7172889,"POLYGON ((-64.70794 18.3467, -64.70803 18.3465..."
29789,78,18100,02414007,7818100,Charlotte Amalie East,Charlotte Amalie East CDP,57,U2,N,N,G4210,S,864051,0,+18.3339781,-064.9157258,"POLYGON ((-64.91468 18.33113, -64.91472 18.331..."
29790,78,19000,02414008,7819000,Charlotte Amalie West,Charlotte Amalie West CDP,57,U2,N,N,G4210,S,5113595,27768,+18.3368927,-064.9720696,"POLYGON ((-64.97124 18.34677, -64.96721 18.347..."
29791,78,65530,02651575,7865530,Red Hook,Red Hook CDP,57,U1,N,N,G4210,S,686129,716711,+18.3236115,-064.8462620,"POLYGON ((-64.8508 18.32866, -64.84968 18.3294..."
29792,78,78300,02413996,7878300,Tutu,Tutu CDP,57,U1,N,N,G4210,S,4296297,28670,+18.3391984,-064.8886168,"POLYGON ((-64.89433 18.3313, -64.89423 18.3324..."

In [4]:
combined_df['GEOID'] = combined_df['GEOID'].astype(str)
combined_gdf['GEOID10'] = combined_gdf['GEOID10'].astype(str)

# Perform a left join on the correct column, including all columns from both DataFrames
result_df = pd.merge(combined_df, combined_gdf, left_on='GEOID', right_on='GEOID10', how='left')




result_df

,GEOID,statename,place,muni,restrict_NA_permit,restrict_NA_units,limit_NA_dwellings,limit_NA_dwelling_units,STATEFP10,PLACEFP10,...,CLASSFP10,PCICBSA10,PCINECTA10,MTFCC10,FUNCSTAT10,ALAND10,AWATER10,INTPTLAT10,INTPTLON10,geometry
0,0203000,AK,Anchorage,AK_Anchorage,0,0,0,0,02,03000,...,C1,Y,N,G4110,A,4.415109e+09,663860984.0,+61.1775490,-149.2743541,"POLYGON ((-149.3618 61.48339, -149.36147 61.48..."
1,0233140,AK,Homer,AK_Homer,0,0,0,0,02,33140,...,C1,N,N,G4110,A,3.581459e+07,33614501.0,+59.6399849,-151.5112337,"POLYGON ((-151.58424 59.66409, -151.5781 59.66..."
2,0238420,AK,Kenai,AK_Kenai,0,0,0,0,02,38420,...,C1,N,N,G4110,A,7.405108e+07,17665909.0,+60.5622743,-151.2079714,"POLYGON ((-151.16643 60.51796, -151.16678 60.5..."
3,0258660,AK,Palmer,AK_Palmer,0,0,0,0,02,58660,...,C1,N,N,G4110,A,1.334647e+07,0.0,+61.5973690,-149.1147635,"POLYGON ((-149.13343 61.61896, -149.13349 61.6..."
4,0260310,AK,Petersburg,AK_Petersburg,0,0,0,0,02,60310,...,C1,N,N,G4110,A,1.142988e+08,3884322.0,+56.7632089,-132.8757405,"POLYGON ((-132.91914 56.80524, -132.91908 56.8..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2634,5621125,WY,Douglas,WY_Douglas,0,0,0,0,56,21125,...,C1,N,N,G4110,A,1.186689e+07,454401.0,+42.7546707,-105.3837977,"MULTIPOLYGON (((-105.36724 42.7733, -105.36693..."
2635,5640120,WY,Jackson,WY_Jackson,0,0,0,0,56,40120,...,C1,Y,N,G4110,A,7.543982e+06,98708.0,+43.4740508,-110.7721929,"MULTIPOLYGON (((-110.77378 43.47613, -110.7741..."
2636,5644760,WY,Lander,WY_Lander,0,0,0,0,56,44760,...,C1,N,N,G4110,A,1.208222e+07,0.0,+42.8309230,-108.7304413,"MULTIPOLYGON (((-108.81016 42.7472, -108.8094 ..."
2637,5645050,WY,Laramie,WY_Laramie,0,0,0,0,56,45050,...,C1,Y,N,G4110,A,4.593487e+07,59517.0,+41.3102405,-105.6096249,"POLYGON ((-105.56658 41.33037, -105.56654 41.3..."
2638,5663900,WY,Rawlins,WY_Rawlins,0,0,0,0,56,63900,...,C1,N,N,G4110,A,2.134604e+07,98642.0,+41.7851690,-107.2240560,"MULTIPOLYGON (((-107.19539 41.78949, -107.1954..."

In [5]:
nan_count = result_df['NAME10'].isna().sum()
nan_count

387

In [6]:
ashford_occurrences = combined_gdf[combined_gdf['NAME10'].str.contains('Avon')]
ashford_occurrences.head()

,STATEFP10,PLACEFP10,PLACENS10,GEOID10,NAME10,NAMELSAD10,LSAD10,CLASSFP10,PCICBSA10,PCINECTA10,MTFCC10,FUNCSTAT10,ALAND10,AWATER10,INTPTLAT10,INTPTLON10,geometry
16,01,03364,02405191,0103364,Avon,Avon town,43,C1,N,N,G4110,A,6855898,53694,+31.1797239,-085.2791835,"POLYGON ((-85.26885 31.19098, -85.26761 31.190..."
992,04,04720,02409765,0404720,Avondale,Avondale city,25,C1,N,N,G4110,A,118097573,139887,+33.3130406,-112.3290768,"POLYGON ((-112.35642 33.43144, -112.35642 33.4..."
3089,06,29644,02408298,0629644,Glen Avon,Glen Avon CDP,57,U1,N,N,G4210,S,20975719,90084,+34.0169247,-117.4828598,"POLYGON ((-117.49818 34.03353, -117.49804 34.0..."
3472,08,04110,02411658,0804110,Avon,Avon town,43,C1,N,N,G4110,A,20794158,177024,+39.6417972,-106.5158769,"MULTIPOLYGON (((-106.49847 39.63126, -106.4957..."
3834,08,04165,02407788,0804165,Avondale,Avondale CDP,57,U1,N,N,G4210,S,3061777,20790,+38.2316592,-104.3455106,"POLYGON ((-104.35892 38.24168, -104.35892 38.2..."

In [7]:

nan_rows = result_df[result_df['INTPTLAT10'].isna()]
nan_rows

,GEOID,statename,place,muni,restrict_NA_permit,restrict_NA_units,limit_NA_dwellings,limit_NA_dwelling_units,STATEFP10,PLACEFP10,...,CLASSFP10,PCICBSA10,PCINECTA10,MTFCC10,FUNCSTAT10,ALAND10,AWATER10,INTPTLAT10,INTPTLON10,geometry
330,0901430,CT,Ashford,CT_Ashford,0,0,0,0,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,None
331,0902060,CT,Avon,CT_Avon,0,0,0,0,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,None
332,0904580,CT,Bethany,CT_Bethany,0,0,0,0,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,None
333,0905910,CT,Bloomfield,CT_Bloomfield,0,0,0,0,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,None
334,0907310,CT,Branford,CT_Branford,0,0,0,0,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,None
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2544,5530075,WI,Grand Chute,WI_GrandChute,0,0,0,0,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,None
2551,5536275,WI,Hudson,WI_Hudson,0,0,0,0,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,None
2572,5551600,WI,Middleton,WI_MiddletonTown,0,0,0,0,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,None
2578,5555075,WI,Mukwonago Town,WI_Mukwonago,0,0,0,0,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,None
2597,5567325,WI,Rib Mountain,WI_RibMountain,0,0,0,0,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,None

In [8]:
for index, row in nan_rows.iterrows():
    place = row['place']
    match_found = False
    for idx, combined_gdf_row in combined_gdf.iterrows():
        name10 = combined_gdf_row['NAME10']
        if place == name10:
            if combined_gdf_row['GEOID10'][:2] == row['GEOID'][:2]:
                #print(combined_row['GEOID10'][:2])
                #print(row['GEOID'][:2])
                print(f"{place} match found")
                combined_gdf.at[idx, 'GEOID10'] = row['GEOID']

Brooklyn match found
Clinton match found
Colchester match found
Darien match found
Durham match found
East Hampton match found
Greenwich match found
Portland match found
Putnam match found
Stratford match found
Waterford match found
Westport match found
Wethersfield match found
Thornton match found
Abington match found
Adams match found
Andover match found
Arlington match found
Barre match found
Belchertown match found
Belmont match found
Burlington match found
Dedham match found
Falmouth match found
Foxborough match found
Hingham match found
Hopkinton match found
Hudson match found
Ipswich match found
Lexington match found
Marshfield match found
Maynard match found
Medfield match found
Milford match found
Nantucket match found
Needham match found
Pepperell match found
Reading match found
Swampscott match found
Topsfield match found
Webster match found
Wellesley match found
Williamstown match found
Wilmington match found
Winchendon match found
Bar Harbor match found
Berwick match found
Dexter match found
Fairfield match found
Farmington match found
Freeport match found
Fryeburg match found
Gray match found
Hampden match found
Kennebunk match found
Livermore Falls match found
Madawaska match found
Madison match found
Millinocket match found
Newport match found
Norridgewock match found
Searsport match found
Skowhegan match found
Thomaston match found
Topsham match found
Waldoboro match found
Wilton match found
Brighton match found
Ypsilanti match found
Amherst match found
Bristol match found
Charlestown match found
Enfield match found
Exeter match found
Farmington match found
Hanover match found
Hudson match found
Jaffrey match found
Londonderry match found
Milford match found
Milton match found
Newmarket match found
Peterborough match found
Andover match found
Florence match found
Freehold match found
Lakewood match found
Old Bridge match found
Raritan match found
Babylon match found
Batavia match found
Gates match found
Huntington match found
Irondequoit match found
Islip match found
Mamaroneck match found
Seneca Falls match found
Smithtown match found
West Seneca match found
Milan match found
Bristol match found
Darby match found
Hampton match found
Kingston match found
Lower Allen match found
Patton match found
Whitehall match found
York match found
Barton match found
Bristol match found
Castleton match found
Chester match found
Hardwick match found
Manchester match found
Richmond match found
Rutland match found
Shelburne match found
Waterbury match found
Windsor match found
Beloit match found
Hudson match found
Middleton match found
Rib Mountain match found

In [9]:
result_df = pd.merge(combined_df, combined_gdf, left_on='GEOID', right_on='GEOID10', how='left')
nan_count = result_df['NAME10'].isna().sum()
nan_count

264

In [10]:
nan_rows = result_df[result_df['NAME10'].isna()]
nan_rows

,GEOID,statename,place,muni,restrict_NA_permit,restrict_NA_units,limit_NA_dwellings,limit_NA_dwelling_units,STATEFP10,PLACEFP10,...,CLASSFP10,PCICBSA10,PCINECTA10,MTFCC10,FUNCSTAT10,ALAND10,AWATER10,INTPTLAT10,INTPTLON10,geometry
330,0901430,CT,Ashford,CT_Ashford,0,0,0,0,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,None
331,0902060,CT,Avon,CT_Avon,0,0,0,0,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,None
332,0904580,CT,Bethany,CT_Bethany,0,0,0,0,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,None
333,0905910,CT,Bloomfield,CT_Bloomfield,0,0,0,0,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,None
334,0907310,CT,Branford,CT_Branford,0,0,0,0,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,None
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2468,5084475,VT,Williston,VT_Williston,1,1,1,1,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,None
2528,5511775,WI,Cady,WI_Cady,0,0,0,0,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,None
2535,5519475,WI,Delavan Town,WI_DelavanTown,0,0,0,0,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,None
2544,5530075,WI,Grand Chute,WI_GrandChute,0,0,0,0,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,None
2578,5555075,WI,Mukwonago Town,WI_Mukwonago,0,0,0,0,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,None

In [14]:
from IPython.display import HTML

# Assuming nan_rows is a DataFrame
html = nan_rows.to_html()

# Display the DataFrame in a scrollable div
HTML(f"""
<div style="height: 400px; overflow: auto;">
    {html}
</div>
""")

In [35]:
Penfield_occurrences = combined_gdf[combined_gdf['NAME10'].str.contains('Penfield')]
Penfield_occurrences.head()

,STATEFP10,PLACEFP10,PLACENS10,GEOID10,NAME10,NAMELSAD10,LSAD10,CLASSFP10,PCICBSA10,PCINECTA10,MTFCC10,FUNCSTAT10,ALAND10,AWATER10,INTPTLAT10,INTPTLON10,geometry
7369,17,58577,02628559,1758577,Penfield,Penfield CDP,57,U1,N,N,G4210,S,666213,0,+40.3047003,-087.9443066,"POLYGON ((-87.9397 40.30881, -87.93957 40.3087..."

In [16]:
result_df = result_df.loc[:, ['INTPTLAT10', 'INTPTLON10', 'GEOID', 'statename', 'place', 'muni', 'restrict_NA_permit', 'restrict_NA_units', 'limit_NA_dwellings', 'limit_NA_dwelling_units']]
result_df

,INTPTLAT10,INTPTLON10,GEOID,statename,place,muni,restrict_NA_permit,restrict_NA_units,limit_NA_dwellings,limit_NA_dwelling_units
0,+61.1775490,-149.2743541,0203000,AK,Anchorage,AK_Anchorage,0,0,0,0
1,+59.6399849,-151.5112337,0233140,AK,Homer,AK_Homer,0,0,0,0
2,+60.5622743,-151.2079714,0238420,AK,Kenai,AK_Kenai,0,0,0,0
3,+61.5973690,-149.1147635,0258660,AK,Palmer,AK_Palmer,0,0,0,0
4,+56.7632089,-132.8757405,0260310,AK,Petersburg,AK_Petersburg,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...
2634,+42.7546707,-105.3837977,5621125,WY,Douglas,WY_Douglas,0,0,0,0
2635,+43.4740508,-110.7721929,5640120,WY,Jackson,WY_Jackson,0,0,0,0
2636,+42.8309230,-108.7304413,5644760,WY,Lander,WY_Lander,0,0,0,0
2637,+41.3102405,-105.6096249,5645050,WY,Laramie,WY_Laramie,0,0,0,0
2638,+41.7851690,-107.2240560,5663900,WY,Rawlins,WY_Rawlins,0,0,0,0

In [17]:
nan_rows = result_df[result_df['INTPTLAT10'].isna()]
nan_rows

,INTPTLAT10,INTPTLON10,GEOID,statename,place,muni,restrict_NA_permit,restrict_NA_units,limit_NA_dwellings,limit_NA_dwelling_units
330,NaN,NaN,0901430,CT,Ashford,CT_Ashford,0,0,0,0
331,NaN,NaN,0902060,CT,Avon,CT_Avon,0,0,0,0
332,NaN,NaN,0904580,CT,Bethany,CT_Bethany,0,0,0,0
333,NaN,NaN,0905910,CT,Bloomfield,CT_Bloomfield,0,0,0,0
334,NaN,NaN,0907310,CT,Branford,CT_Branford,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...
2468,NaN,NaN,5084475,VT,Williston,VT_Williston,1,1,1,1
2528,NaN,NaN,5511775,WI,Cady,WI_Cady,0,0,0,0
2535,NaN,NaN,5519475,WI,Delavan Town,WI_DelavanTown,0,0,0,0
2544,NaN,NaN,5530075,WI,Grand Chute,WI_GrandChute,0,0,0,0
2578,NaN,NaN,5555075,WI,Mukwonago Town,WI_Mukwonago,0,0,0,0

In [29]:
import pandas as pd
import plotly.express as px

# Sample DataFrame
data =  nan_rows[['statename']]
df = pd.DataFrame(data)

# Count occurrences of each state
state_counts = df['statename'].value_counts().reset_index()
state_counts.columns = ['state', 'count']
state_counts

total_value_counts = combined_df['statename'].value_counts().reset_index()
total_value_counts.columns = ['state', 'count']
total_value_counts

merged_df = pd.merge(state_counts, total_value_counts, on='state', how='right')
merged_df['count_x'] = merged_df['count_x'].fillna(0)
merged_df['ratio'] = merged_df['count_x'] / merged_df['count_y']
merged_df.head()

  state  count_x  count_y     ratio
0    CA      0.0      184  0.000000
1    PA     69.0      182  0.379121
2    TX      0.0      157  0.000000
3    IL      0.0      142  0.000000
4    OH      9.0      135  0.066667

In [32]:

# Create a choropleth map
fig = px.choropleth(merged_df,
                    locations='state',
                    locationmode='USA-states',
                    color='ratio',
                    scope='usa',
                    color_continuous_scale='Viridis',
                    title='NaN/Sample_Total Places')

# Update layout to adjust figure size
fig.update_layout(
    width=800,  # Set the width of the figure
    height=600  # Set the height of the figure
)

fig.show()

In [33]:
result_df = result_df.dropna()
result_df

,INTPTLAT10,INTPTLON10,GEOID,statename,place,muni,restrict_NA_permit,restrict_NA_units,limit_NA_dwellings,limit_NA_dwelling_units
0,+61.1775490,-149.2743541,0203000,AK,Anchorage,AK_Anchorage,0,0,0,0
1,+59.6399849,-151.5112337,0233140,AK,Homer,AK_Homer,0,0,0,0
2,+60.5622743,-151.2079714,0238420,AK,Kenai,AK_Kenai,0,0,0,0
3,+61.5973690,-149.1147635,0258660,AK,Palmer,AK_Palmer,0,0,0,0
4,+56.7632089,-132.8757405,0260310,AK,Petersburg,AK_Petersburg,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...
2634,+42.7546707,-105.3837977,5621125,WY,Douglas,WY_Douglas,0,0,0,0
2635,+43.4740508,-110.7721929,5640120,WY,Jackson,WY_Jackson,0,0,0,0
2636,+42.8309230,-108.7304413,5644760,WY,Lander,WY_Lander,0,0,0,0
2637,+41.3102405,-105.6096249,5645050,WY,Laramie,WY_Laramie,0,0,0,0
2638,+41.7851690,-107.2240560,5663900,WY,Rawlins,WY_Rawlins,0,0,0,0

In [36]:
result_df['restrict/limit_none'] = result_df[['restrict_NA_permit', 'restrict_NA_units', 'limit_NA_dwellings', 'limit_NA_dwelling_units']].max(axis=1)
result_df

C:\Users\clint\AppData\Local\Temp\ipykernel_9488\3620297966.py:1: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

,INTPTLAT10,INTPTLON10,GEOID,statename,place,muni,restrict_NA_permit,restrict_NA_units,limit_NA_dwellings,limit_NA_dwelling_units,restrict/limit_none
0,+61.1775490,-149.2743541,0203000,AK,Anchorage,AK_Anchorage,0,0,0,0,0
1,+59.6399849,-151.5112337,0233140,AK,Homer,AK_Homer,0,0,0,0,0
2,+60.5622743,-151.2079714,0238420,AK,Kenai,AK_Kenai,0,0,0,0,0
3,+61.5973690,-149.1147635,0258660,AK,Palmer,AK_Palmer,0,0,0,0,0
4,+56.7632089,-132.8757405,0260310,AK,Petersburg,AK_Petersburg,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...
2634,+42.7546707,-105.3837977,5621125,WY,Douglas,WY_Douglas,0,0,0,0,0
2635,+43.4740508,-110.7721929,5640120,WY,Jackson,WY_Jackson,0,0,0,0,0
2636,+42.8309230,-108.7304413,5644760,WY,Lander,WY_Lander,0,0,0,0,0
2637,+41.3102405,-105.6096249,5645050,WY,Laramie,WY_Laramie,0,0,0,0,0
2638,+41.7851690,-107.2240560,5663900,WY,Rawlins,WY_Rawlins,0,0,0,0,0

In [40]:
import pandas as pd
import folium
from folium import IFrame

# Step 1: Load the data
# Assuming you have a DataFrame with columns: 'longitude', 'latitude', 'binary_variable'
data = result_df

# Step 2: Create a base map centered on North America
m = folium.Map(location=[54.5260, -105.2551], zoom_start=4)

# Step 3: Add red points to the map first
for _, row in data.iterrows():
    if row['restrict/limit_none'] != 1:
        folium.CircleMarker(
            location=[row['INTPTLAT10'], row['INTPTLON10']],
            radius=5,
            color='red',
            fill=True,
            fill_color='red'
        ).add_to(m)

# Step 4: Add green points to the map last
for _, row in data.iterrows():
    if row['restrict/limit_none'] == 1:
        folium.CircleMarker(
            location=[row['INTPTLAT10'], row['INTPTLON10']],
            radius=5,
            color='green',
            fill=True,
            fill_color='green'
        ).add_to(m)

# Step 5: Create an HTML template with a title
title_html = '''
             <h3 align="center" style="font-size:20px"><b>Restrict_NA_Permit</b></h3>
             '''
m.get_root().html.add_child(folium.Element(title_html))

# Step 6: Save the map to an HTML file
m.save('restrict_limit_none.html')